const translations = {
    en: {
      restaurantName: "PizzaPizza",
      signup: "Sign Up",
      email: "Email *",
      password: "Password *",
      confirmPassword: "Password (repeat) *",
      firstName: "First name *",
      lastName: "Last name *",
      phoneNumber: "Telephone number *",
      postalCode: "Postal code *",
      address: "Address *",
      house: "House *",
      stairs: "Stairs (optional)",
      stick: "Stick (optional)",
      door: "Door",
      bell: "Bell (optional)",
      comment: "Comment on your address (optional)",
      agreeTerms: "I agree to the terms and conditions.",
      reset: "Reset",
      cancel: "Cancel",
      addToBasket: "Add to basket",
      searchMenu: "Search in Menu",
      close: "Close",
      forgotPassword: "Forgot password?",
      logout: "Log Out",
      proceedToCheckout: "Review payment and address",
      total: "Total",
      basketEmpty: "Your basket is empty",
      yourBasket: "Your items",
      basketSummary: "Summary",
      checkout: {
        postalCode: "Postal Code",
        selectPostalCode: "Select Postal Code",
        address: "Address",
        selectAddress: "Select Address",
        loading: "Loading...",
        error: {
          fetchingPostcodes: "Error fetching postal codes",
          fetchingAddresses: "Error fetching addresses"
        }
      },
      orderMethod: "Order Method",
      delivery: "Delivery",
      selfCollection: "Pickup",
      phone: "Phone *",
      specialNotes: "Special Notes (Optional)",
      completeOrder: "Complete Order",
      totalAmount: "Total Amount",
      homePageTitle: "Welcome to Our Restaurant",
      welcomeMessage: "Welcome to Pizza Vienna ",
      welcomeText:
        "At Pizza Vienna, we serve more than just food — we serve the best culinary experience in town. Our menu is crafted with passion, featuring a wide selection of delicious, handcrafted dishes made from the freshest, high-quality ingredients.",
      contactUs: "Feel free to explore our menu or contact us for any inquiries.",
      optional: "optional",
      restaurantDescription: "Come and try our delicious menu!",
      orderNow:"Order Now",
      visitUs: "Visit Us",
      openingHours: "Opening Hours",
      openDaily: "Open Daily",
      contact: "Contact",
      phoneNumber: "+43 123 456 789",
      location: "Location",
      address: "Vienna, Austria",
      paymentSuccess: {
        title: "Payment Successful!",
        loading: "Loading...",
        error: "Error",
        completed: "Payment Completed",
        processing: "Payment Processing",
        pending: "Payment Pending",
        unknown: "Unknown Status",
        cashPending: "Order Pending - Pay at Pickup",
        orderDetails: "Order Details",
        orderNumber: "Order Number",
        total: "Total",
        paymentMethod: "Payment Method",
        orderMore: "Order More",
        returnHome: "Return to Home"
      },
      promotions: "Promotions",
      free: "Free",
      specialInstructions: "Special Instructions",
      addNote: "Add any special instructions or notes..."
    }, 
    tr: {
      restaurantName: "PizzaPizza",
      signup: "Kayıt Ol",
      email: "E-posta *",
      password: "Şifre *",
      confirmPassword: "Şifreyi Tekrarla *",
      firstName: "Ad *",
      lastName: "Soyad *",
      phoneNumber: "Telefon numarası *",
      postalCode: "Posta kodu *",
      address: "Adres *",
      house: "Ev *",
      stairs: "Kat (isteğe bağlı)",
      stick: "Sopa (isteğe bağlı)",
      door: "Kapı",
      bell: "Zil (isteğe bağlı)",
      comment: "Yorum (isteğe bağlı)",
      agreeTerms: "Şartlar ve koşulları kabul ediyorum.",
      reset: "Sıfırla",
      cancel: "İptal",
      addToBasket: "Sepete Ekle",
      searchMenu: "Menüde Ara",
      basketSummary: "Sepet Özeti",
      close: "Kapat",
      forgotPassword: "Şifremi unuttum?",
      logout: "Çıkış Yap",
      proceedToCheckout: "Sepeti Onayla",
      total: "Toplam",
      basketEmpty: "Sepetiniz şuan boş",
      yourBasket: "Ürünleriniz",
      checkout: {
        postalCode: "Posta Kodu",
        selectPostalCode: "Posta Kodu Seçin",
        address: "Adres",
        selectAddress: "Adres Seçin",
        loading: "Yükleniyor...",
        error: {
          fetchingPostcodes: "Posta kodları alınırken hata oluştu",
          fetchingAddresses: "Adresler alınırken hata oluştu"
        }
      },
      orderMethod: "Sipariş Yöntemi",
      delivery: "Teslimat",
      selfCollection: "Gel-Al ",
      phone: "Telefon *",
      specialNotes: "Özel Notlar (Opsiyonel)",
      completeOrder: "Siparişi Tamamla",
      totalAmount: "Toplam Miktar",
      welcomeMessage: "Pizza Vienna'ya Hoşgeldiniz",
      welcomeText:
        "Pizza Vienna'da sadece yemek değil, aynı zamanda şehrin en iyi mutfak deneyimini sunuyoruz. Menümüz, taze ve kaliteli malzemelerle hazırlanmış, özenle seçilmiş el yapımı lezzetlerle doludur.",
      contactUs: "Menümüzü keşfetmekten veya bizimle iletişime geçmekten çekinmeyin.",
      optional: "isteğe bağlı",
      summary:"Sipariş Özeti",
      orderNow:"Sipariş Ver",
      visitUs: "Bizi Ziyaret Edin",
      openingHours: "Çalışma Saatleri",
      openDaily: "Her Gün Açık",
      contact: "İletişim",
      phoneNumber: "+43 123 456 789",
      location: "Konum",
      address: "Viyana, Avusturya",
      paymentSuccess: {
        title: "Ödeme Başarılı!",
        loading: "Yükleniyor...",
        error: "Hata",
        completed: "Ödeme Tamamlandı",
        processing: "Ödeme İşleniyor",
        pending: "Ödeme Beklemede",
        unknown: "Bilinmeyen Durum",
        cashPending: "Sipariş Beklemede - Teslimatta Ödeyin",
        orderDetails: "Sipariş Detayları",
        orderNumber: "Sipariş Numarası",
        total: "Toplam",
        paymentMethod: "Ödeme Yöntemi",
        orderMore: "Tekrar Sipariş Ver",
        returnHome: "Ana Sayfaya Dön"
      },
      promotions: "Kampanyalar",
      free: "Ücretsiz",
      specialInstructions: "Özel Talimatlar",
      addNote: "Özel talimat veya not ekleyin..."
    }
  };
  
  export default translations;
  